name: test
on:
  pull_request:
  push: 
    branches: 
      - main
env:
  LOG_LEVEL: info
  SWIFT_DETERMINISTIC_HASHING: 1

jobs:

  unit-tests:
    uses: vapor/ci/.github/workflows/run-unit-tests.yml@reusable-workflows
    with:
      with_coverage: true
      with_tsan: true
  
  upstream-check:
    runs-on: ubuntu-latest
    container: swift:5.7
    steps:
      - name: Check out self
        uses: actions/checkout@v3
        with:
          path: routing-kit
      - name: Check out Vapor
        uses: actions/checkout@v3
        with:
          repository: vapor/vapor
          path: vapor
      - name: Use local package
        run: swift package --package-path vapor edit routing-kit --path routing-kit
      - name: Run tests
        run: swift test --package-path vapor

  test-exports:
      name: Test exports
      runs-on: ubuntu-latest
      steps:
        - name: Check out Vapor
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Build
          run: swift build -Xswiftc -DBUILDING_DOCC
